service:
  name: quik-2-converter
  provider-code: QUIK:VTB
  standard-settings-controller.enabled: true
  simple-worker:
    enabled: true
    name: simple-worker
    wait-on-stop-ms: 5000
    wait-on-restart-ms: 20000
    min-time-per-iteration-ms: 3000
    timeout-runner-life-ms: 60000
    print-statistics-every-ms: 1000
  kafka:
    server: localhost:9092
    income-topics:
      standard-loader.enabled: true
      standard-offsets-controller.enabled: true
    outcome-topics:
      standard-uploader.enabled: true
  redis:
    income-collections:
      standard-loader.enabled: true
  offsets-controller:
    type: file
    file-storage: offets.data
  messages:
    standard-queue:
      enabled: true
      name: messages-queue
      max-queue-size: 5000
      print-statistics-every-ms: 1000
      priorities-count: 4
    standard-executor:
      enabled: true
      name: messages-executor
      wait-on-stop-ms: 5000
      wait-on-restart-ms: 20000
      min-time-per-iteration-ms: 1000
      timeout-runner-life-ms: 60000
      print-statistics-every-ms: 1000
  channels-api:
    quik-provider-streams:
      securities-v1.enabled: true
      orders-v1.enabled: true
      deals-v1.enabled: true
      all-trades-v1.enabled: true
    quik-provider-snapshots:
      securities-v1.enabled: true
    fics-snapshots:
      securities-v1.enabled: true
      currencies-v1.enabled: true
      derivatives-v1.enabled: true
    md-streams:
      md-trades-v1.enabled: true
      md-orders-v1.enabled: true
      md-deals-v1.enabled: true

# Логирование
logging:
  level:
    org.springframework: info
    org.springframework.orm: info
    org.springframework.web: info

# Настройки Сервера
server:
  port: 7103

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true